package com.magho.annotations;

import org.springframework.stereotype.Component;

@Component
public class ExperiencedVendor implements Employee{
    @Override
    public String getTasks() {
        return "Sell our products";
    }

    @Override
    public String getReport() {
        return "Report generated by the vendor";
    }
}
